# Generated by Django 2.1.5 on 2019-02-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banned_shops',
            field=models.ManyToManyField(blank=True, related_name='disliked_shops', to='Challenge.Shop'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_shops',
            field=models.ManyToManyField(blank=True, related_name='liked_shops', to='Challenge.Shop'),
        ),
    ]
